# Generated by Django 5.1.7 on 2025-04-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=models.TextField(null=True, verbose_name='Статья'),
        ),
    ]
